syms s_th c_th s_ps c_ps;
A_psi = [1, 0, 0; 0,c_ps, s_ps; 0, -s_ps, c_ps];
A_theta = [c_th, 0, -s_th; 0, 1, 0; s_th, 0, c_th];
e_phi = [0; 0; 1];
e_theta = [0; 1; 0];
e_psi = [1; 0; 0];
disp("A_psi = ");
disp(A_psi);
disp("A_theta = ");
disp(A_theta);
disp("e_phi = ");
disp(e_phi);
disp("e_theta = ");
disp(e_theta);
disp("e_psi = ");
disp(e_psi);
Binv = [A_psi*A_theta*e_phi, A_psi*e_theta, e_psi];
disp("B^-1 = ");
pretty(Binv);
B = inv(Binv);
disp("B = ");
pretty(B);
